[build]
publish = "../../public"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[build.environment]
HUGO_THEMESDIR = "../.."
HUGO_VERSION = "0.57.0"
